### ISSUE TITLE
False error when config matches stderr_re

### ISSUE THREAD

**Issue by yuandongx** [ansible-collections/cisco.asa#84]
[Line](https://github.com/ansible-collections/cisco.asa/blob/117c6a5c2be5862cb792e444ec92608865fda0bb/plugins/terminal/asa.py#L39) can also match "error:"  which is commented in `access-list remark`, for example:
```access-list test-acl-001 remark error: this is a error test.```
And other line included `error:` will also match it.

**Comment by yuandongx** [comment]
cc @pabelanger @CaptTrews

**Comment by Qalthos** [comment]
So the stderr_re list can be overridden on a per-task basis to avoid this sort of thing by following https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#task-failure-due-to-mismatched-error-regex-within-command-response-using-ansible-netcommon-network-cli-connection-type

As `re.compile("error", re.I)` is basically the only thing that catches errors on asa, I would suggest either proceeding with caution and trying to minimize the amount of time that regex is ignored or (preferably) rewording your remark so that it doesn't trip that regex.
